# Template for new NixOS server
# Copy this file and customize for your server
#
# Steps to add a new server:
# 1. Copy this file to hosts/nixos/<server-name>.nix
# 2. Update the hostname and hardware configuration
# 3. Add any server-specific packages or services
# 4. Create a home config in home/<user>-<server>.nix if needed
# 5. Add the configuration to flake.nix:
#
#    "<server-name>" = mkNixosSystem {
#      hostname = "<server-name>";
#      user = "<username>";
#      hostConfig = ./hosts/nixos/<server-name>.nix;
#      homeConfig = import ./home/<user>.nix;
#    };
#
{ pkgs, ... }:
{
  imports = [
    ../../modules/nixos/common.nix
    # ./hardware-configuration.nix  # Generated by nixos-generate-config
  ];

  # Hostname
  networking.hostName = "server-name";

  # Boot loader (adjust for your system)
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";

  # Additional packages for this server
  environment.systemPackages = with pkgs; [
    # Add server-specific packages here
  ];

  # User configuration
  users.users.isala = {
    isNormalUser = true;
    home = "/home/isala";
    shell = pkgs.fish;
    extraGroups = [
      "wheel"
      "docker"
    ];
    openssh.authorizedKeys.keys = [
      # Add your SSH public keys here
      # "ssh-ed25519 AAAA..."
    ];
  };

  # Additional services
  # services.docker.enable = true;
  # services.nginx.enable = true;

  # Additional firewall ports
  # networking.firewall.allowedTCPPorts = [ 80 443 ];
}
